profiles = {
  'permissive': {
    "allow": [
      "Bash(awk:*)",
      "Bash(cat:*)",
      "Bash(cp:*)",
      "Bash(cut:*)",
      "Bash(date:*)",
      "Bash(df:*)",
      "Bash(echo:*)",
      "Bash(find:*)",
      "Bash(head:*)",
      "Bash(htop:*)",
      "Bash(id:*)",
      "Bash(ls:*)",
      "Bash(mkdir:*)",
      "Bash(printf:*)",
      "Bash(ps:*)",
      "Bash(pwd:*)",
      "Bash(rg:*)",
      "Bash(sed:*)",
      "Bash(sort:*)",
      "Bash(tail:*)",
      "Bash(top:*)",
      "Bash(touch:*)",
      "Bash(tr:*)",
      "Bash(uname:*)",
      "Bash(uniq:*)",
      "Bash(uptime:*)",
      "Bash(wc:*)",
      "Bash(where:*)",
      "Bash(which:*)",
      "Bash(whoami:*)",
      "Read",
      "Edit",
      "Create",
      "Write",
      "Grep",
      "Glob",
      "LS",
      "WebFetch(domain:github.com)",
      "WebFetch(domain:docs.*)",
      "WebFetch(domain:raw.githubusercontent.com)",
      "WebFetch(domain:stackoverflow.com)",
      "mcp__spackle-probe__search_code",
      "mcp__spackle-probe__query_code",
      "mcp__spackle-probe__extract_code",
      "mcp__spackle-main__build",
      "mcp__spackle-main__run",
      "mcp__spackle-main__test",
      "mcp__spackle-main__create_task",

    ],
    "deny": [
      "Bash(grep:*)"      
    ]
  }
}